import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })
interface FeedFormType {
  getRss: React.FormEventHandler<HTMLFormElement>
  handleOnChange: React.ChangeEventHandler<HTMLInputElement>
}

export default function Home({ getRss, handleOnChange }: FeedFormType) {
  return (
    <>
      {/* <Head>
        <title>Rss Reader Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <div>
        <h3>URL</h3>
        <form onSubmit={getRss}>
        <input type="url" name="rssurl" id="rssurl"
          placeholder="Add an URL"
          onChange={(e) => { handleOnChange(e) } }
          required
          />
        <button type="submit">Add
        </button>
      </form>
      </div>
    </>
  )
}
